cnn = nn.Sequential()
cnn:add( nn.SpatialConvolution(1, 20, 3, 3, 2, 2) )
cnn:add( nn.Dropout(opt.dropout) )
cnn:add( nn.ReLU() )
cnn:add( nn.SpatialConvolution(20, 15, 3, 3, 2, 2) )
cnn:add( nn.Dropout(opt.dropout) )
cnn:add( nn.ReLU() )
cnn:add( nn.SpatialConvolution(15, 10, 5, 5, 3, 3) )
cnn:add( nn.Dropout(opt.dropout) )
cnn:add( nn.ReLU() )
cnn:add( nn.SpatialConvolution(10, 600, 19, 34) )
cnn:add( nn.Dropout(opt.dropout) )
cnn:add( nn.ReLU() )
cnn:add( nn.View(1, 600) )
